Create ShoppingCartPage
ProjectCIMS/TuDa.CIMS pull request #115
Opened 2024-12-17 20:40 UTC by anngy12

There is still something not working when clicking the Button to open up the SubmitPopup.

2025-01-05 15:45 UTC, Sc3l3t0n requested changes
I think the merge of #97 was a bit flaky. I hope I found all things

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Entities/Substance.cs
> +    public string Purity { get; set; }
🔧 This should not be changed. Maybe a failure in the merging

2025-01-05 15:45 UTC, Sc3l3t0n commented on infrastructure/TuDa.CIMS.MigrationService/Worker.cs
> +                if (!await dbContext.AssetItems.ContainsAsync(assetItems[0], cancellationToken))
🔧 Same thing here

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/Pages/ShoppingCartPage.razor
> +            <PurchaseEntryList Purchase="@Purchase" AssetItemDeleted="_=>StateHasChanged()"/>
⛏️ You could improve the readablity a bit
```suggestion
            <PurchaseEntryList Purchase="@Purchase" AssetItemDeleted="@(_ => StateHasChanged())"/>
```

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/Pages/ShoppingCartPage.razor.cs
> +        };
🤔 Is Buyer here requiered?
If so lets change that or set it to `null!`

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/Pages/ShoppingCartPage.razor.cs
> +        Product = assetItem;
🔧 Remove `Product` here and just use `assetItem`

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/Pages/ShoppingCartPage.razor.cs
> +            "Amount Input",
🔧 To German

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/Pages/ShoppingCartPage.razor.cs
> +            }
🔧 🤔  Amount is not nullable here when the result is a success, is it?

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/Pages/ShoppingCartPage.razor.cs
> +    public required IDialogService DialogService { get; set; }
🔧 To private and set it to `null!`
```suggestion
    private IDialogService _dialogService { get; set; } = null!;
```

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/Pages/ShoppingCartPage.razor.cs
> +            },
🔧 This is only needed at the moment. Maybe add a todo to remove it 😄

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/Pages/ShoppingCartPage.razor.cs
> +            "Submit Input",
🔧 To german

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/Pages/ShoppingCartPage.razor.cs
> +        }
🔧 You need to use the resulted `WorkingGroup` here and set the `WorkingGroup` of the Purchase here and not creating a new instance.
```suggestion
       var workingGroup = await dialog.GetReturnValueAsync<WorkingGroup>();
        if (workingGroup is not null)
        {
            Purchase.WorkingGroup = workingGroup;
        }
```

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/Pages/ShoppingCartPage.razor.cs
> +    }
🔧 Add the Product as a parameter

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/Pages/ShoppingCartPage.razor.cs
> +            }
We could think about creating a Constructor to only give the `Amount` and `AssetItem` as parameter, so the `Price` is automatically copied from the `AssetItem.`

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingCart/PurchaseEntryList.razor
> +﻿@namespace TuDa.CIMS.Web.Components.ShoppingCart
🤔 Is this necessary here?

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingCartFooter.razor
> +
🤔 Same here

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingCartProductDialog.razor
> +﻿@namespace TuDa.CIMS.Web.Components.ShoppingCart
🤔 Same here

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingCartSubmitPopup.razor
> +@namespace TuDa.CIMS.Web.Components.ShoppingCart
🤔 Same here

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingCartSubmitPopup.razor
> +                <ShoppingCartSubmitPopupPurchaseList PurchaseEntries="PurchaseEntries"/>
🔧 I think the old version was the right one. Maybe a merge error

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingCartSubmitPopupPurchaseList.razor
> +    <MudPaper Height="300px" Width="400px" Style="overflow-y: auto;">
🔧 Same here, the removed thing should not be removed

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingCartSubmitPopupPurchaseList.razor.cs
> +            },
🔧 Same here

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingCartSubmitPopupWorkingGroupSelection.razor
> +<MudItem Class="d-flex align-items-center" Style="margin-bottom: 300px;">
🔧 The `margin-bottom` was removed before. Merge error

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingCartSubmitPopupWorkingGroupSelection.razor.cs
> +    public WorkingGroup WorkingGroup { get; set; }
🔧 Same here. Merge Error

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingSearch.razor
> +@namespace TuDa.CIMS.Web.Components.ShoppingCart
🔧 I think this can be infered

2025-01-05 15:45 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/Dashboard/AssetList.razor
> +@namespace TuDa.CIMS.Web.Components.Dashboard
🔧 Can be removed. Will be inferred

2025-01-05 16:43 UTC, anngy12 commented on src/TuDa.CIMS.Web/Components/Pages/ShoppingCartPage.razor.cs
> +        }
Purchase does not have a working group anymore only a Buyer. Changes are needed in Purchase or in ShoppingCartSubmitPopup.

2025-01-05 17:10 UTC, anngy12 commented on src/TuDa.CIMS.Web/Components/Pages/ShoppingCartPage.razor.cs
> +            }
constructor? where exactly?

2025-01-05 20:21 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/Pages/ShoppingCartPage.razor.cs
> +        }
You're right. We will need to extract the sending of the purchase to the API to another ticket, because we need the ticket #129

2025-01-05 20:22 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/Pages/ShoppingCartPage.razor.cs
> +            }
In `PurchaseEntry`, but It's not really necessary

2025-01-06 16:30 UTC, Sc3l3t0n approved these changes

2025-01-06 17:31 UTC, devidsdt approved these changes

2025-01-07 13:36 UTC, merged