Add missing fields to person and derived types
ProjectCIMS/TuDa.CIMS pull request #131
Opened 2024-12-19 21:44 UTC by devidsdt

I knew it was not much to do. I hope I did not forget something.

2025-01-08 11:14 UTC, tom03k approved these changes

2025-01-08 12:33 UTC, Sc3l3t0n requested changes

2025-01-08 12:33 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Entities/Enums/Gender.cs
> +    Divers
🔧 I would suggest english enum member names

2025-01-08 12:33 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Entities/Professor.cs
> +    public int? ZipCode { get; set; } = null;
🔧 ZipCodes are not an Integer because they can start with 0. So we need a string here

2025-01-08 12:33 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Entities/Professor.cs
> +    public string StreetAndNumber { get; set; } = string.Empty;
🔧 I would split that into two fields

2025-01-08 12:33 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Entities/Professor.cs
> +    public string City { get; set; } = string.Empty;
🔧 I would merge this into an `Address` entity

2025-01-08 12:33 UTC, Sc3l3t0n commented on test/TuDa.CIMS.Shared.Test/Faker/PersonFaker.cs
> +﻿using System.Data;
❓ Is this needed?

2025-01-08 12:33 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Entities/Person.cs
> +    public Gender Salutation { get; set; } = Gender.Divers;
❓  Why is this called Salutation?

2025-01-08 12:33 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Entities/Enums/Gender.cs
> +    Divers
🤔 Maybe add an `Unknown` field?

2025-01-08 12:52 UTC, devidsdt commented on src/TuDa.CIMS.Shared/Entities/Enums/Gender.cs
> +    Divers
I thought this will be used in the invoice generation and working group page. So i chose the german ones.

2025-01-08 12:56 UTC, devidsdt commented on src/TuDa.CIMS.Shared/Entities/Person.cs
> +    public Gender Salutation { get; set; } = Gender.Divers;
Forgot to change the comment. But the reason is like in the comment before, I think it's easier to use the salutation directly for our use, doesn't it?

2025-01-08 14:17 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Entities/Person.cs
> +    public Gender Salutation { get; set; } = Gender.Divers;
I generated the Salutation from the Gender in my PR #122.
And it's not the salutation. For example `Herr` -> `Herrn`

2025-01-08 14:19 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Entities/Enums/Gender.cs
> +    Divers
Generally, `Enums` members should be in the main language of the code.
I chose to switch on the enum values and create the `Salutation` there.

2025-01-09 15:05 UTC, Sc3l3t0n requested changes
Only the Migration is important

2025-01-09 19:14 UTC, Sc3l3t0n requested changes

2025-01-09 19:14 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Migrations/20250109162536_AddMissingPersonFields.cs
This looks a bit weird

2025-01-09 19:14 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Database/CIMSDbContext.cs
> +        });
❓ Why this if you could just add an address as a new `DBEntity` and add it as an `DBSet` here?

2025-01-10 00:16 UTC, devidsdt commented on src/TuDa.CIMS.Api/Database/CIMSDbContext.cs
> +        });
Forgot to let Address inherit from BaseEntity. So I tried to fix the occured error, but you are right

2025-01-10 12:49 UTC, Sc3l3t0n approved these changes

2025-01-10 16:18 UTC, anngy12 approved these changes

2025-01-10 16:49 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Migrations/20250110010253_AddAdress.cs
> +                onDelete: ReferentialAction.Cascade);
❗ The person here will cause issues, please rebase to new main and redo the migration

2025-01-11 13:37 UTC, Sc3l3t0n approved these changes
Works on my machine without any problems. The table is created successfully.

2025-01-11 13:38 UTC, merged