4 filter
ProjectCIMS/TuDa.CIMS pull request #18
Opened 2024-11-15 16:15 UTC by anngy12

2024-11-15 17:26 UTC, Sc3l3t0n requested changes

2024-11-15 17:26 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/FilterComponent.razor
> +@code {
🔧Could you press "Alt-Str-L" to format the file?

2024-11-15 17:26 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/FilterComponent.razor
> +private List<string> Keywords { get; set; } = new List<string> { "Keyword", "Key", "Word" };
⛏️ You could use a collection expression
```suggestion
private List<string> Keywords { get; set; } = ["Keyword", "Key", "Word"];
```

2024-11-15 17:26 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/FilterComponent.razor
> +};
⛏️ Here the same
```suggestion
private List<CheckboxItem> CheckboxItems { get; set; } =
[
new CheckboxItem { Label = "Label", Description = "Description" },
new CheckboxItem { Label = "Label", Description = "Description" },
new CheckboxItem { Label = "Label", Description = "Description" }
];
```

2024-11-15 17:26 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/FilterComponent.razor
> +}
🔧The Attributes of the class could be null at the end of the Constructor. Maybe we should require them.
```suggestion
private class CheckboxItem
{
    public require string Label { get; set; }
    public require string Description { get; set; }
}
```

2024-11-15 17:26 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/FilterComponent.razor
> +                    @keyword <button class="btn-close btn-close-white btn-sm ms-2-5" @onclick="() => RemoveKeyword(keyword)"></button>
🤔 For shorter line width we could think about something like
```suggestion
                    @keyword 
                    <button class="btn-close btn-close-white btn-sm ms-2-5" 
                            @onclick="() => RemoveKeyword(keyword)">
                    </button>
```

2024-11-15 17:26 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/FilterComponent.razor
> +            <label for="priceSlider" class="form-label"><strong>Label</strong></label>
🔧 Lets not nest multiple HTML elements in one line
```suggestion
            <label for="priceSlider" 
                   class="form-label">
                <strong>Label</strong>
            </label>
```

2024-11-15 21:50 UTC, Sc3l3t0n requested changes
After this I'm completely happy

2024-11-15 21:50 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/FilterComponent.razor
>                  <label class="form-check-label" for="@item.Label">
🔧 Can you move the attributes in their own line too?

2024-11-15 21:50 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/FilterComponent.razor
> +            <label for="priceSlider" class="form-label">
🔧 Can you move the attributes in their own line too?

2024-11-16 00:56 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/FilterComponent.razor
> +﻿@* FilterComponent *@
Sorry for the inconvenience, but you need to change the name of the component and file to `Filter` like I described in #21

2024-11-16 02:05 UTC, Sc3l3t0n requested changes
Sorry for the thing with #19 and #21
After this, I'm happy with everything 👍
Looks nice btw👀

2024-11-16 02:05 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/FilterComponent.razor
> +                            @onclick="() => RemoveKeyword(keyword)">
🔧 Sorry, I made a mistake with the formatting. We can format it like this, but the way it's mentioned in #19 is easier to read IMO
```suggestion
                    <button 
                        class="btn-close btn-close-white btn-sm ms-2"
                        @onclick="() => RemoveKeyword(keyword)"
                    >
```

2024-11-16 02:05 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/FilterComponent.razor
> +                <input class="form-check-input" type="checkbox" value="" id="@item.Label">
🔧 Like the above

2024-11-16 02:05 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/FilterComponent.razor
> +            <input type="range" class="form-range" id="priceSlider">
🔧 Like the above

2024-11-16 14:04 UTC, Sc3l3t0n commented
Approved

2024-11-16 15:52 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/Filter.razor
:wrench: I know I'm going round in circles, but the formatting I wanted is not supported for razor files in Rider. So please run format again, and then I'm finally happy :sob:. Sorry for this mess :hankey:

2024-11-16 16:13 UTC, anngy12 commented on src/TuDa.CIMS.Web/Components/Filter.razor
what do you mean with run format again? STRG + ALT + L maybe?

2024-11-16 16:44 UTC, Sc3l3t0n approved these changes

2024-11-17 12:08 UTC, devidsdt approved these changes

2024-11-17 13:25 UTC, merged