Search
ProjectCIMS/TuDa.CIMS pull request #25
Opened 2024-11-17 09:45 UTC by devidsdt

Reopened the PR, I forgot to rebase the changes in main branch.

2024-11-17 10:32 UTC, Sc3l3t0n requested changes

2024-11-17 10:32 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/AssetSearch.razor
> +    rel="stylesheet"/>
:thinking: Is this really necessary? I thought the icons are included in the normal package

2024-11-17 10:32 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/AssetSearch.razor
> +           style="top: 50%; right: 15px; transform: translateY(-50%); color: #aaa;">
:wrench: Can we use bootstrap classes for that, or extract this to `AssetSearch.razor.css` as a new class?

2024-11-17 10:32 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/AssetSearch.razor
> +           id="prototypeSearchBar"
:thinking: Do you need this?

2024-11-17 10:46 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/AssetSearch.razor
> +    rel="stylesheet"/>
Ok, it actually is.

2024-11-17 11:15 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/AssetSearch.razor
> +    rel="stylesheet"/>
:wrench: You can also just move this to `App.razor`, but then add a TODO comment above it.

2024-11-17 12:47 UTC, Sc3l3t0n commented
For what are the `woff` files needed?

2024-11-17 12:48 UTC, Sc3l3t0n requested changes

2024-11-17 12:48 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/AssetSearch.razor
> +            class="bi bi-search position-absolute top-50 end-0 translate-middle-y text-secondary">
⛏️ Could be converted to a single line

2024-11-17 13:00 UTC, devidsdt commented
> For are the `woff` files needed for?

Otherwise Blazor does not find the icons

2024-11-17 13:07 UTC, Sc3l3t0n approved these changes

2024-11-18 12:09 UTC, anngy12 approved these changes

2024-11-18 12:29 UTC, merged