AssetItem-Entity
ProjectCIMS/TuDa.CIMS pull request #38
Opened 2024-11-22 16:08 UTC by devidsdt

2024-11-22 18:08 UTC, Sc3l3t0n requested changes
🔧 Make all required fields required and all non required field optional, or give them a default value. Something like lists and string should have a respective empty as default.

2024-11-22 18:08 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Entities/AssetItem.cs
> +    public List<Hazard>? Hazards { get; set; }
```suggestion
    public List<Hazard> Hazards { get; set; } = [];
```

2024-11-22 18:08 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Entities/AssetItem.cs
> +    public string Note { get; set; }
```suggestion
    public string Note { get; set; } = string.Empty;
```

2024-11-22 18:13 UTC, Sc3l3t0n requested changes
🔧 Add some short comments to the entities like
```csharp
/// <summary>
/// An entitity representing an item in the chemical inventory.
/// </summary>
public record AssetItem()
{
    /// <summary>
    /// An unique identifier for chemicals.
    /// </summary>
    public string Cas { get; set; }
```

2024-11-22 18:16 UTC, Sc3l3t0n requested changes
❓ I changed the entity diagram around a bit. Maybe you can take a look and tell me your thoughts. Especially of the separation for devices and chemicals.
[PR](https://github.com/ProjectCIMS/TuDa.CIMS.Docs/pull/8)

2024-11-23 15:06 UTC, devidsdt commented
> ❓ I changed the entity diagram around a bit. Maybe you can take a look and tell me your thoughts. Especially of the separation for devices and chemicals. [PR](https://github.com/ProjectCIMS/TuDa.CIMS.Docs/pull/8)

I agree with the changes. I just would change the name of the class from "device" to "consumables". I guess it describes "Verbrauchsmaterialien" in a better way. And we could add the "Artikelnummer" and the shop of the bought items.

2024-11-23 15:34 UTC, devidsdt commented on src/TuDa.CIMS.Shared/TuDa.CIMS.Shared.csproj
> +    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.6" />
Should be compatible according to my research. I will change it anyway, so we just use the path to the image.

2024-11-23 16:20 UTC, Sc3l3t0n requested changes
⛏️ You can use this plugin and use it to format the files so it's consistent
https://plugins.jetbrains.com/plugin/18243-csharpier

2024-11-23 16:22 UTC, Sc3l3t0n reviewed
🔧 On all records, the `()` after the name and the `;` at the end is obsolete and should be removed

2024-11-23 16:22 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Entities/AssetItem.cs
> +public record AssetItem()
```suggestion
public record AssetItem
```

2024-11-23 16:22 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Entities/AssetItem.cs
> +};
```suggestion
}
```

2024-11-23 16:27 UTC, Sc3l3t0n requested changes
🔧 The inheritance from the diagram is missing. I know the Diagram is a total mess 😢

2024-11-23 16:27 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Entities/Chemical.cs
> +public record Chemical()
🔧 The inheritance to `AssetItem` is missing
```suggestion
public record Chemical : AssetItem
```

2024-11-23 16:27 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Entities/Consumables.cs
> +public record Consumables()
🔧 Same here
```suggestion
public record Consumables : AssetItem
```

2024-11-23 16:27 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Entities/Chemical.cs
> +    public required string ItemNumber { get; set; }
🔧 Move this to `AssetItem` because it's a common of `Chemical` and `Consumables`

2024-11-23 16:27 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Entities/Consumables.cs
> +    public required string ItemNumber { get; set; }
🔧 Same as above

2024-11-23 16:35 UTC, Sc3l3t0n commented
> > ❓ I changed the entity diagram around a bit. Maybe you can take a look and tell me your thoughts. Especially of the separation for devices and chemicals. [PR](https://github.com/ProjectCIMS/TuDa.CIMS.Docs/pull/8)
> 
> I agree with the changes. I just would change the name of the class from "device" to "consumables". I guess it describes "Verbrauchsmaterialien" in a better way. And we could add the "Artikelnummer" and the shop of the bought items.

Yes, that is a way better name. I will adapt the diagram.

2024-11-23 16:39 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Entities/Consumables.cs
> +public record Consumables()
🔧 Class names should be singular
```suggestion
public record Consumable
```

2024-11-23 16:44 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Entities/AssetItem.cs
> +public record AssetItem()
🌱 This should be abstract, so only sub records can be actually created
```suggestion
public abstract record AssetItem
```

2024-11-23 17:28 UTC, Sc3l3t0n approved these changes
Some formatting is weird but fuck it 😆

2024-11-23 17:36 UTC, devidsdt commented
> Some formatting is weird but fuck it 😆

Sorry, forgot to fix it

2024-11-23 19:27 UTC, Sc3l3t0n commented
No problem, now its perfekt 💯

2024-11-24 12:16 UTC, alina612 approved these changes

2024-11-24 13:35 UTC, merged