simple AssetItem functionality
ProjectCIMS/TuDa.CIMS pull request #46
Opened 2024-11-27 15:32 UTC by alina612

Added GetAll, GetOne, Update and Remove functionality for AssetItem. 

The programm.cs file was automatically formatted and I didn't change it itentionally. I only added:

builder.Services.AddScoped<IAssetItemRepository, AssetItemRepository>();
builder.Services.AddScoped<IAssetItemService, AssetItemService>();
builder.Services.AddControllers();

2024-11-28 17:28 UTC, devidsdt approved these changes

2024-12-01 19:03 UTC, Sc3l3t0n requested changes
🔧 Update dtos should normally not have any default values, so you can check for null when updating the entity.

2024-12-01 19:04 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Dtos/UpdateAssetItemDto.cs
> +public class UpdateAssetItemDto
🤔 This could be made abstract

2024-12-01 19:07 UTC, Sc3l3t0n reviewed
⛏️ The dtos can be transformed into a record

2024-12-01 19:33 UTC, Sc3l3t0n requested changes
I know you were not finished, but I wrote some comments where I saw something

2024-12-01 19:33 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Controllers/AssetItemController.cs
> +    [HttpPut($"{{{nameof(id)}:guid}}/{{{nameof(updateModel)}:AssetItem}}")]
🔧 The `AssetItem` should be transferred in the body and not be necessary in the route
```suggestion
    [HttpPut($"{{{nameof(id)}:guid}}")]
```

2024-12-01 19:33 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Controllers/AssetItemController.cs
> +        return Ok();
🔧 Only send an `Ok` if the service did not fail

2024-12-01 19:33 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Controllers/AssetItemController.cs
> +        return Ok();
🔧 Only send an `Ok` if the service did not fail

2024-12-01 19:33 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Repositories/AssetItemRepository.cs
> +        throw new NotImplementedException();
🔧 Can be removed safely

2024-12-01 19:33 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Repositories/AssetItemRepository.cs
> +    }
🔧 Decide whether to handle errors with `Optionals` like in the return type or with Exceptions, done by the `SingleAsync`

2024-12-01 19:33 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Repositories/AssetItemRepository.cs
> +        existingItem.Name = updateModel.Name ?? existingItem.Name;
🔧 Use the correct field of `existingItem` for updating

2024-12-01 19:33 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Repositories/AssetItemRepository.cs
> +        }
🤔 Maybe a default branch which returns an Error would be helpful here.

2024-12-01 19:33 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Repositories/AssetItemRepository.cs
> +        existingItem.Room.Id = updateModel.RoomId ?? existingItem.Room.Id;
🔧 You should not check if the existing room is null, rather check if the RoomId of the `dto` does not correlate to one in the database and then return an `NotFound`. Also, do not set the ID of the room. Rather, set the Room property to the retrieved room from the database. Before everything, we should check if the room should be updated at all
```suggestion
        if (updateModel.RoomId is not null) {
            var room = await _context.Rooms.SingleOrDefaultAsync(r => r.Id == updateModel.RoomId);
            if (room is null)
            {
                return Error.NotFound(
                    "Assetitem.update",
                    $"Given RoomId {updateModel.RoomId} was not found."
                );
            }
            existingItem.Room = room;
        }
```

2024-12-01 19:33 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Repositories/AssetItemRepository.cs
> +            .SingleAsync();
🔧 With the `ErrorOr` as return type, you should use SingleOrDefaultAsync() and check for null to return a `NotFound` if so.

2024-12-01 19:33 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Services/AssetItemService.cs
> +            return Result.Updated;
🔧  Just return the value of the repo

2024-12-01 19:33 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Services/AssetItemService.cs
> +            return Result.Deleted;
🔧 Just return the value of service

2024-12-01 19:34 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Controllers/AssetItemController.cs
> +            .ToErrorOr()
🔧 Need to be removed

2024-12-02 18:35 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Repositories/AssetItemRepository.cs
> +                return Error.NotFound();
⛏️ Return a Conflict and mention what's wrong here

2024-12-03 10:18 UTC, Sc3l3t0n requested changes
Some minor things

2024-12-03 10:18 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/ConfigureServices.cs
> +            options.Servers = [];
🌱 Maybe add a comment, that this is needed to clear the cashed IPs to work with Aspire

2024-12-03 10:18 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Controllers/AssetItemController.cs
> +    }
🔧 Remove this testing leftover

2024-12-03 10:18 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Repositories/AssetItemRepository.cs
> +                return Error.NotFound(
🔧 This should be a conflict or failure

2024-12-03 10:18 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Services/AssetItemService.cs
> +                null => Error.Failure(
🔧 Should be `NotFound` as error type

2024-12-04 16:08 UTC, Sc3l3t0n approved these changes

2024-12-04 16:11 UTC, merged