Add pagination to AssetList
ProjectCIMS/TuDa.CIMS pull request #61
Opened 2024-12-05 13:23 UTC by devidsdt

2024-12-06 12:55 UTC, Sc3l3t0n commented
Can you add this in the DbContext
```cs
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder
            .Entity<AssetItem>()
            .HasOne(a => a.Room)
            .WithMany()
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<AssetItem>().Navigation(a => a.Room).AutoInclude();
}
```

2024-12-06 14:15 UTC, Sc3l3t0n requested changes

2024-12-06 14:15 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Controllers/AssetItemController.cs
> +    [HttpGet]
🔧 This needs to be unique so `GetAll` and this does not clash
```suggestion
    [HttpGet("paginated")]
```

2024-12-06 14:15 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Repositories/AssetItemRepository.cs
> +        return items;
⛏️ You could merge this into one statement

2024-12-06 14:15 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Dtos/PaginatedResponse.cs
> +        var items = await source.Skip((pageNumber - 1) * pageSize).Take(pageSize).ToListAsync();
🌱 For slightly better performance, you could parallelize this. I would look something like this:
```suggestion
        var countTask = source.CountAsync();
        var itemsTask = source.Skip((pageNumber - 1) * pageSize).Take(pageSize).ToListAsync();

        Task.WaitAll(countTask, itemsTask);
        
        return new PaginatedResponse<T>(await itemsTask, await countTask, pageNumber, pageSize);
```

2024-12-06 14:15 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Params/UserParams.cs
> +public class UserParams
🔧 🌱 I would rename this to a more declarative name, something like `AssetItemPaginationQueryParams`, so we can use multiple query parameters

2024-12-06 14:15 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/TuDa.CIMS.Shared.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
🤔 I don't think we should add this here, because the FE does not need to have EF as dependency.

2024-12-06 14:15 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Shared/Dtos/PaginatedResponse.cs
> +}
🤔 To fix the above, we could move this into a `FactoryClass` and into the API project to not leak any API code to the FE.

2024-12-10 16:03 UTC, Sc3l3t0n approved these changes

2024-12-10 16:03 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Factories/PaginatedResponseFactory.cs
> +public class PaginatedResponseFactory<T>
⛏️ Should be static IMO

2024-12-20 11:22 UTC, anngy12 approved these changes

2024-12-20 11:34 UTC, merged