Create AssetItemPopup
ProjectCIMS/TuDa.CIMS pull request #95
Opened 2024-12-13 17:26 UTC by anngy12

ProductPage is an example to show it is used.
ProductDialog is the actual AssetItemPopup.

2024-12-15 16:15 UTC, Sc3l3t0n requested changes

2024-12-15 17:17 UTC, Sc3l3t0n commented
Please rename the components to a more scoped name.

I would suggest adding `ShoppingCart` as a prefix.

2024-12-16 13:39 UTC, anngy12 commented on src/TuDa.CIMS.Web/Components/ProductDialog.razor
> +                              Type="number"/>
I got an error while using uint. But I found another good alternative to resolve the problem with negative numbers.
```suggestion
                <MudTextField @bind-Value="Amount"
                              Error="@isError"
                              ErrorText="Amount must be a positive number"
                              InputMode="@InputMode.numeric"
                              InputType="@InputType.Number"
                              Label="Amount"
                              T="int"/>
```

2024-12-16 14:16 UTC, anngy12 commented on src/TuDa.CIMS.Web/Components/ProductPage.razor
> +        return DialogService.ShowAsync<ProductDialog>("Amount Input", parameters, options);
Console.WriteLine(await dialog.GetReturnValueAsync<uint>()); 
throws an error, when the dialog is closed through cancel

```suggestion
        return DialogService.ShowAsync<ProductDialog>("Amount Input", parameters, options);
```

2024-12-17 16:47 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingCartProductDialog.razor.cs
> +    private bool isError => Amount <= 0;
🔧 Should be `IsError`

2024-12-17 16:48 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingCartProductDialog.razor.cs
> +    public required ILogger<ShoppingCartProductDialog> Logger { get; set; }
🔧 Should be private

2024-12-17 16:52 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingCartProductDialog.razor.cs
> +            Entries.Add(PurchaseEntry);
🔧 This stuff should be handled by the Page

2024-12-17 17:18 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingCartProductDialog.razor.cs
> +    public EventCallback<int> OnAmountSubmitted { get; set; }
🔧 This is not needed because, that's returned when running Submit.

2024-12-17 19:42 UTC, Sc3l3t0n approved these changes

2024-12-17 19:56 UTC, devidsdt approved these changes

2024-12-17 19:57 UTC, merged