64 search for assetitem
ProjectCIMS/TuDa.CIMS pull request #99
Opened 2024-12-14 17:12 UTC by alina612

This pr also includes #75. 
Only the following files were changed:

src/TuDa.CIMS.Web/Services/IAssetItemApi.cs
src/TuDa.CIMS.Api/Repositories/AssetItemRepository.cs
src/TuDa.CIMS.Api/Interfaces/IAssetItemRepository.cs
src/TuDa.CIMS.Api/Interfaces/IAssetItemService.cs
src/TuDa.CIMS.Api/Services/AssetItemService.cs
src/TuDa.CIMS.Api/Controllers/AssetItemController.cs
src/TuDa.CIMS.Web/Components/ShoppingSearch.razor
src/TuDa.CIMS.Web/Components/ShoppingSearch.razor.cs

The search bar needs to be placed in the correct position in the ShoppingCartPage ticket.
![search](https://github.com/user-attachments/assets/6778c316-6451-4926-9f8e-79bcccf5d560)

2024-12-15 15:12 UTC, Sc3l3t0n requested changes

2024-12-15 15:12 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Controllers/AssetItemController.cs
> +    public async Task<IActionResult> GetAllAsync([Query] string? nameOrCas)
🔧 Unfortunately, that's the wrong attribute. This is from `Refit,` but we need the `FromQuery` from Asp.Net
```suggestion
    public async Task<IActionResult> GetAllAsync([FromQuery] string? nameOrCas)
```

2024-12-15 15:12 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Interfaces/IAssetItemService.cs
> +    Task<ErrorOr<IEnumerable<AssetItem>>> GetAllAsync([Query] string? nameOrCas);
🔧 Attribute does nothing here
```suggestion
    Task<ErrorOr<IEnumerable<AssetItem>>> GetAllAsync(string? nameOrCas);
```

2024-12-15 15:12 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Services/AssetItemService.cs
> +    public async Task<ErrorOr<IEnumerable<AssetItem>>> GetAllAsync([Query] string? nameOrCas)
🔧 Attribute does nothing here

2024-12-15 15:12 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingSearch.razor
> +            @bind-Value="selectedItem":
🔧 Remove this here
```suggestion
            @bind-Value="selectedItem"
```

2024-12-15 15:12 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingSearch.razor.cs
> +    private AssetItem selectedItem;
🔧 Can be safely removed

2024-12-15 15:20 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Api/Repositories/AssetItemRepository.cs
> +        //TODO fix include hazards
🔧 The changes should be merged and you can include the Hazards again

2024-12-16 00:23 UTC, Sc3l3t0n requested changes

2024-12-16 00:23 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingSearch.razor.cs
> +    private async Task SelectAssetItem(AssetItem item)
⛏️  Would rename it to `AssetItemSelectedInternal`

2024-12-16 00:23 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingSearch.razor
> +        </MudAutocomplete>
🔧 Add back in the `ValueChanged`. I found out what were wrong, you need to add the Type back in and then he takes a normal function as parameter.
```suggestion
        <MudAutocomplete
            T="AssetItem"
            @ref="_autocomplete"
            Clearable="@true"
            AdornmentIcon="@Icons.Material.Filled.Search"
            AdornmentColor="@Color.Primary"
            Label="Items"
            SearchFunc="@Search"
            ToStringFunc="@ToString"
            ValueChanged="@AssetItemSelectedInternal"
            Variant="Variant.Filled"
            Dense=true
            ShowProgressIndicator="true">
        </MudAutocomplete>
```

2024-12-16 00:23 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingSearch.razor.cs
> +    private MudAutocomplete<AssetItem> _autocomplete;
🔧 Add this to suppress the warning
```suggestion
    private MudAutocomplete<AssetItem> _autocomplete = null!; // Is set by blazor component
```

2024-12-16 00:23 UTC, Sc3l3t0n commented on src/TuDa.CIMS.Web/Components/ShoppingSearch.razor.cs
> +        };
🔧 I got a null dereference error, so maybe add a null case. 
```suggestion
    private static string ToString(AssetItem item) =>
        item switch
        {
            Substance substance => $"{substance.Name} ({substance.Cas})",
            null => "",
            _ => item.Name,
        };
```

2024-12-17 11:13 UTC, Sc3l3t0n approved these changes

2024-12-17 14:20 UTC, anngy12 approved these changes

2024-12-17 14:27 UTC, merged